<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>🗑️ Regression Challenge - Linear Model Interpretability</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This report investigates the dangers of trusting linear regression models when relationships are non-linear. We analyze how even carefully constructed regression models can produce misleading results when the assumption of linearity is violated, even if relationships appear monotonic.</p>
<p><strong>True Relationship:</strong> We know that Anxiety = Stress + 0.1 × Time, where: - Anxiety is measured by fMRI activity - Stress is measured by cortisol level in blood - Time is the number of minutes on social media in the last 24 hours</p>
<p><strong>True Coefficients:</strong> - Intercept (<span class="math inline">\(\beta_0\)</span>) = 0 - Stress coefficient (<span class="math inline">\(\beta_1\)</span>) = 1 - Time coefficient (<span class="math inline">\(\beta_2\)</span>) = 0.1</p>
<p><strong>Key Problem:</strong> In practice, we often can’t measure stress directly with expensive blood tests. Instead, we use surveys (StressSurvey) as a proxy. This proxy has a monotonic relationship with true stress but is non-linear. We’ll see how this non-linearity causes regression to fail.</p>
<section id="the-data-generation-process" class="level3">
<h3 class="anchored" data-anchor-id="the-data-generation-process">The Data Generation Process</h3>
<div class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>observDF</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Notice that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> indeed holds perfectly. Also, notice the addition of a <code>StressSurvey</code> column. This data was generated by a survey (instead of a blood test) to be a proxy for measuring stress levels using expensive and unpleasant blood tests. You can see it’s a good proxy as there is a <em>monotonic</em> (and a sorta-kinda <em>linear</em>) relationship between the survey results and actual measured stress levels (see <a href="#fig-stress-proxy" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
<p>I. <strong>Bivariate Regression Analysis with StressSurvey:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="bivariate-regression-stresssurvey" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
MANUAL CALCULATION OF REGRESSION COEFFICIENT
============================================================
Mean of StressSurvey (x̄): 6.0000
Mean of Anxiety (ȳ): 4.7580

Numerator: Σ(xi - x̄)(yi - ȳ) = 282.6900
Denominator: Σ(xi - x̄)² = 270.0000

Manual calculation:
  Coefficient (β₁) = 282.6900 / 270.0000 = 1.0470
  Intercept (β₀) = 4.7580 - 1.0470 × 6.0000 = -1.5240

Sklearn verification:
  Coefficient (β₁) = 1.0470
  Intercept (β₀) = -1.5240
============================================================

============================================================
BIVARIATE REGRESSION: Anxiety on StressSurvey
============================================================
Intercept (β₀): -1.5240
Coefficient on StressSurvey (β₁): 1.0470
R-squared: 0.9011

True Relationship: Anxiety = Stress + 0.1 × Time
Note: StressSurvey is a proxy for Stress
True coefficient on Stress (if we had it): β₁ = 1.0

Comparison:
  Estimated coefficient: 1.0470
  True Stress coefficient: 1.0
  Difference: 0.0470
============================================================</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The bivariate regression of Anxiety on StressSurvey produces the following estimated coefficients:</p>
<ul>
<li><strong>Intercept (β₀):</strong> The intercept value from the regression output above</li>
<li><strong>Coefficient on StressSurvey (β₁):</strong> The slope coefficient from the regression output above</li>
<li><strong>R-squared:</strong> The R² value indicating model fit</li>
</ul>
<p><strong>Comparison to True Relationship:</strong></p>
<p>The true relationship is: <strong>Anxiety = Stress + 0.1 × Time</strong>, where: - The true coefficient on Stress (β₁) = <strong>1.0</strong> - The true intercept (β₀) = <strong>0</strong></p>
<p>However, when we regress Anxiety on StressSurvey (a proxy for Stress), we find:</p>
<ol type="1">
<li><p><strong>The estimated coefficient differs from 1.0:</strong> The regression produces a coefficient that is not equal to 1.0, even though StressSurvey is intended to measure the same underlying construct as Stress.</p></li>
<li><p><strong>Why the discrepancy occurs:</strong></p>
<ul>
<li><strong>Omitted variable bias:</strong> This bivariate regression excludes Time, which is part of the true relationship. The omission of Time causes the coefficient on StressSurvey to be biased.</li>
<li><strong>Proxy measurement error:</strong> StressSurvey is a non-linear proxy for the true Stress variable. While StressSurvey and Stress have a monotonic relationship, the non-linearity means that a one-unit increase in StressSurvey does not correspond to a one-unit increase in Stress. This measurement error propagates through the regression, causing the coefficient estimate to deviate from the true value.</li>
<li><strong>Non-linear relationship:</strong> The relationship between StressSurvey and Anxiety is not perfectly linear, but linear regression forces a linear fit, leading to incorrect coefficient estimates.</li>
</ul></li>
<li><p><strong>Key insight:</strong> Even though StressSurvey appears to be a “good” proxy for Stress (monotonic relationship, high correlation), using it in a linear regression produces coefficient estimates that are systematically wrong. This demonstrates that <strong>proxy variables with non-linear relationships to the true variables can lead to misleading regression results</strong>, even when the proxy seems reasonable at first glance.</p></li>
<li><p><strong>The danger:</strong> If a researcher were to interpret the estimated coefficient as the true effect of stress on anxiety, they would be making a fundamental error. The regression coefficient tells us about the relationship between StressSurvey and Anxiety, not the true relationship between Stress and Anxiety.</p></li>
</ol>
<ol start="2" type="I">
<li><strong>Visualization of Bivariate Relationship:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div id="cell-bivariate-regression-stresssurvey-plot" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="bivariate-regression-stresssurvey-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/bivariate-regression-stresssurvey-plot-output-1.png" width="758" height="469" class="figure-img"></p>
<figcaption>Scatter plot with regression line: Anxiety on StressSurvey</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Fit Summary:
  R² = 0.9011
  This means the model explains 90.11% of the variance in Anxiety</code></pre>
</div>
</div>
<p><strong>Analysis of Fit and Potential Issues:</strong></p>
<p>The scatter plot reveals several important insights about the bivariate regression of Anxiety on StressSurvey:</p>
<ol type="1">
<li><p><strong>Visual Fit Assessment:</strong> The regression line appears to capture the general upward trend in the data, with most points clustering relatively close to the line. However, careful inspection shows that the relationship may not be perfectly linear.</p></li>
<li><p><strong>R-squared Interpretation:</strong> The R² value from the regression output indicates how well the model fits the data. While a high R² suggests a reasonably good fit, it does not guarantee that the coefficient estimates are correct or that the relationship is truly linear.</p></li>
<li><p><strong>Key Issues to Consider:</strong></p>
<ul>
<li><strong>Omitted Variable Bias:</strong> This bivariate regression excludes Time, which is part of the true relationship (Anxiety = Stress + 0.1 × Time). This omission could bias the coefficient on StressSurvey.</li>
<li><strong>Proxy Variable Problem:</strong> StressSurvey is a proxy for the true Stress variable. The non-linear relationship between StressSurvey and the actual Stress level means that even if Stress has a linear relationship with Anxiety, StressSurvey may not.</li>
<li><strong>Non-Linearity:</strong> The relationship between StressSurvey and Anxiety may be non-linear, but linear regression forces a linear fit. This could lead to misleading coefficient estimates.</li>
<li><strong>Coefficient Interpretation:</strong> The estimated coefficient differs from the true Stress coefficient of 1.0. This discrepancy suggests that using StressSurvey as a proxy introduces measurement error that affects the regression results.</li>
</ul></li>
<li><p><strong>What the Visualization Tells Us:</strong> The scatter plot allows us to visually inspect whether the linear assumption holds. If we see systematic patterns in the residuals (points consistently above or below the line in certain regions), this would indicate non-linearity that the regression model cannot capture. The visualization helps us understand that even when a regression appears to fit well (high R²), the underlying relationship may not be linear, leading to incorrect coefficient estimates.</p></li>
</ol>
<ol start="3" type="I">
<li><strong>Bivariate Regression Analysis with Time:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="85fdfa38" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
BIVARIATE REGRESSION: Anxiety ~ Time
============================================================

Intercept (beta_0): -3.6801
Coefficient on Time (beta_2): 5.3406
R-squared: 0.5630

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Tue, 11 Nov 2025   Prob (F-statistic):            0.00127
Time:                        21:46:09   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong> Bivariate regression of Anxiety ~ Time gives an intercept around -3.68 and a slope on Time about 5.34, with R² ≈ 0.56. The true data-generating process only assigns 0.1 to Time, so this single-variable regression wildly overstates the time effect. The distortion comes from omitted-variable bias: stress drives both anxiety and time in the dataset, and once you leave stress out, the regression loads that shared variation onto Time, yielding the misleading 5.34 estimate.</p>
<p><strong>Comparison to True Relationship:</strong></p>
<p>The true relationship is: <strong>Anxiety = Stress + 0.1 × Time</strong>, where: - The true coefficient on Time (beta_2) = <strong>0.1</strong> - The true intercept (beta_0) = <strong>0</strong></p>
<p>However, when we regress Anxiety on Time, we find:</p>
<ol type="1">
<li><p><strong>The estimated coefficient differs from 0.1:</strong> The regression produces a coefficient that is not equal to 0.1, even though Time is part of the true relationship.</p></li>
<li><p><strong>Why the discrepancy occurs:</strong></p>
<ul>
<li><strong>Omitted variable bias:</strong> This bivariate regression excludes Stress, which is part of the true relationship. The omission of Stress causes the coefficient on Time to be biased.</li>
<li><strong>Non-linear relationship:</strong> The relationship between Time and Anxiety is not perfectly linear, but linear regression forces a linear fit, leading to incorrect coefficient estimates.</li>
</ul></li>
<li><p><strong>Key insight:</strong> Even though Time appears to be a “good” predictor of Anxiety (linear relationship, high correlation), using it in a linear regression produces coefficient estimates that are systematically wrong. This demonstrates that <strong>predictors with non-linear relationships to the true variable can lead to misleading regression results</strong>, even when the predictor seems reasonable at first glance.</p></li>
<li><p><strong>The danger:</strong> If a researcher were to interpret the estimated coefficient as the true effect of time on anxiety, they would be making a fundamental error. The regression coefficient tells us about the relationship between Time and Anxiety, not the true relationship between Stress and Anxiety.</p></li>
</ol>
<ol start="4" type="I">
<li><strong>Visualization of Bivariate Relationship:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety.</li>
</ol>
<div id="cell-bivariate-regression-time-plot" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stderr">
<pre><code>C:\soujanya\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="bivariate-regression-time-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/bivariate-regression-time-plot-output-2.png" width="758" height="469" class="figure-img"></p>
<figcaption>Scatter plot with regression line: Anxiety on Time</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Fit Summary:
  R² = 0.9011
  This means the model explains 90.11% of the variance in Anxiety</code></pre>
</div>
</div>
<p>Answer: The scatter plot shows a positive relationship between Time and Anxiety, with most points clustering relatively close to the regression line. The R² value indicates that the model explains about 56% of the variance in Anxiety.</p>
<p>V. <strong>Multiple Regression Analysis:</strong> Run a multiple regression of Anxiety on both StressSurvey and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="multiple-regression-stresssurvey-time" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
MULTIPLE REGRESSION: Anxiety on StressSurvey and Time
============================================================

Intercept (beta_0): 0.5888
Coefficient on StressSurvey (beta_1): 1.4269
Coefficient on Time (beta_2): -2.7799
R-squared: 0.9350

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Tue, 11 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        21:46:09   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong> Those figures are the fitted statistics for the multiple regression Anxiety ~ StressSurvey + Time: Intercept ≈ 0.5888 StressSurvey coefficient ≈ 1.4269 Time coefficient ≈ -2.7799 R² ≈ 0.9350 The true data-generating process was Anxiety = Stress + 0.1 × Time, so both slope estimates are off: the proxy StressSurvey overstates the stress effect (1.4269 vs 1.0), and the time coefficient flips sign and becomes large and negative instead of the true -2.7799. The high R² just means the model still fits the sample well, not that the coefficients are trustworthy; the non-linear proxy and the collinearity between stress and time push the interpretation in the wrong direction.</p>
<p><strong>Comparison to True Relationship:</strong> Multiple regression of Anxiety on StressSurvey and Time gives an intercept around 0.5888, a coefficient on StressSurvey around 1.4269, and a coefficient on Time around -2.7799, with R² ≈ 0.9350. The true data-generating process assigns 1 to Stress, 0.1 to Time, and the intercept is 0, so this multiple regression captures both stress and time effects. The coefficients are close to the true values, and the model explains about 93.5% of the variance in Anxiety.</p>
<p><strong>Key Questions:</strong></p>
<ul>
<li><p>Are your estimated coefficients close to these true values? No.&nbsp;Using StressSurvey and Time, we got roughly β₀ ≈ 0.59, β₁ ≈ 1.43, β₂ ≈ -2.78, while the truth is 0, 1, 0.1. The proxy is nonlinear, so the stress effect inflates and the time effect flips sign.</p></li>
<li><p>If not, what does this tell you about the reliability of your regression model? When key inputs are measured with nonlinear proxies (or drivers are omitted), the regression picks up proxy quirks instead of the real relationship. Statistical significance doesn’t rescue those coefficients—they’re biased.</p></li>
<li><p>Even if your R-squared is high, are the coefficients telling the right story? No.&nbsp;R² measures fit, not truth. Even if a model fits well, its coefficients can be wrong if the relationship is non-linear or if key drivers are omitted.</p></li>
</ul>
</section>
<section id="questions-to-answer-for-85-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-85-grade-on-challenge">Questions to Answer for 85% Grade on Challenge</h3>
<ol start="6" type="I">
<li><strong>Multiple Regression Analysis:</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="multiple-regression-stress-time" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
MULTIPLE REGRESSION: Anxiety ~ Stress + Time
============================================================

Intercept (beta_0): -0.0000
Coefficient on Stress (beta_1): 1.0000
Coefficient on Time (beta_2): 0.1000
R-squared: 1.0000

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.600e+31
Date:                Tue, 11 Nov 2025   Prob (F-statistic):          1.15e-187
Time:                        21:46:09   Log-Likelihood:                 493.62
No. Observations:                  15   AIC:                            -981.2
Df Residuals:                      12   BIC:                            -979.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.11e-16   1.02e-15      0.109      0.915   -2.11e-15    2.34e-15
Stress         1.0000   1.15e-16   8.67e+15      0.000       1.000       1.000
Time           0.1000   8.12e-16   1.23e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        3.041   Durbin-Watson:                   0.639
Prob(Omnibus):                  0.219   Jarque-Bera (JB):                1.362
Skew:                           0.357   Prob(JB):                        0.506
Kurtosis:                       1.709   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong> Those figures are the fitted statistics for the multiple regression Anxiety ~ Stress + Time: Intercept ≈ -0.0000 Stress coefficient ≈ 1.0000 Time coefficient ≈ 0.1000 R² ≈ 1.0000 The true data-generating process was Anxiety = Stress + 0.1 × Time, so both slope estimates are off: the stress coefficient overstates the stress effect (1.0000 vs 1.0), and the time coefficient is small and positive instead of the true 0.1000. The high R² just means the model still fits the sample well, not that the coefficients are trustworthy; the collinearity between stress and time pushes the interpretation in the wrong direction.</p>
<p><strong>Comparison to True Relationship:</strong></p>
<p>Multiple regression of Anxiety on Stress and Time gives an intercept around -0.0000, a coefficient on Stress around 1.0000, and a coefficient on Time around 0.1000, with R² ≈ 1.0000. The true data-generating process assigns 1 to Stress, 0.1 to Time, and the intercept is 0, so this multiple regression captures both stress and time effects. The coefficients are close to the true values, and the model explains about 100% of the variance in Anxiety.</p>
<ol start="7" type="I">
<li><strong>Model Comparison:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</li>
</ol>
<div id="cell-model-comparison" class="cell" data-execution_count="10">
<div id="model-comparison" class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">R_squared</th>
<th data-quarto-table-cell-role="th">Adj_R_squared</th>
<th data-quarto-table-cell-role="th">Const_est</th>
<th data-quarto-table-cell-role="th">Const_pvalue</th>
<th data-quarto-table-cell-role="th">StressSurvey_est</th>
<th data-quarto-table-cell-role="th">StressSurvey_pvalue</th>
<th data-quarto-table-cell-role="th">Time_est</th>
<th data-quarto-table-cell-role="th">Time_pvalue</th>
<th data-quarto-table-cell-role="th">Tags</th>
<th data-quarto-table-cell-role="th">Stress_est</th>
<th data-quarto-table-cell-role="th">Stress_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Anxiety ~ StressSurvey + Time</td>
<td>0.935005</td>
<td>0.924173</td>
<td>5.887578e-01</td>
<td>0.579542</td>
<td>1.426926</td>
<td>0.000003</td>
<td>-2.779944</td>
<td>2.781595e-02</td>
<td>proxy + time</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Anxiety ~ Stress + Time</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.110223e-16</td>
<td>0.915218</td>
<td>NaN</td>
<td>NaN</td>
<td>0.100000</td>
<td>5.563718e-164</td>
<td>true stress + time</td>
<td>1.0</td>
<td>3.737032e-186</td>
</tr>
</tbody>
</table>

</div>
<p>Comparing StressSurvey vs Stress multiple regressions</p>
</div>
</div>
</section>
<section id="questions-to-answer-for-95-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-95-grade-on-challenge">Questions to Answer for 95% Grade on Challenge</h3>
<ol start="8" type="I">
<li><strong>Reflect on Real-World Implications:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer? Model 1 (using StressSurvey + Time) produces a big negative slope on time, so the popular press headline would read something like “More Minutes on Social Media Slash Anxiety Levels.” Model 2 (using true Stress + Time) recovers the tiny positive 0.1 slope, so you’d see “Stress Drives Anxiety; Social Media Time Has Only a Minor Effect.” A parent already wary of social media will latch onto the dramatic first headline because it locks in their confirmation bias (either “see, heavy use makes kids calmer” or “the study is obviously flawed”). The social platforms prefer the second model: it says their apps barely move the needle once stress is measured correctly.</li>
</ol>
</section>
<section id="questions-to-answer-for-100-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-100-grade-on-challenge">Questions to Answer for 100% Grade on Challenge</h3>
<ol start="9" type="I">
<li><strong>Avoiding Misleading Statistical Significance:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</li>
</ol>
<div id="subset-regression" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.366e+30
Date:                Tue, 11 Nov 2025   Prob (F-statistic):           1.75e-91
Time:                        21:46:09   Log-Likelihood:                 301.93
No. Observations:                   9   AIC:                            -597.9
Df Residuals:                       6   BIC:                            -597.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         2.887e-16   6.31e-16      0.458      0.663   -1.26e-15    1.83e-15
StressSurvey     0.3333   2.17e-16   1.53e+15      0.000       0.333       0.333
Time             0.1000   8.46e-16   1.18e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        7.901   Durbin-Watson:                   0.278
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                2.800
Skew:                          -1.261   Prob(JB):                        0.247
Kurtosis:                       4.051   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong> I split the data at StressSurvey ≤ 6, keeping only the low-to-moderate regime where the survey proxy is almost linear, ran Anxiety ~ StressSurvey + Time, and got coefficients close to the truth with both slopes statistically significant—showing that a smart subset (plus checking the proxy’s shape) prevents the misleading negative time effect we saw in the full samples</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 For 100% Grade: Focus on What’s Most Interesting
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The key insight:</strong> Linear regression can give you statistically significant results that are completely wrong. The challenge is understanding when and why this happens.</p>
<p><strong>What to investigate:</strong></p>
<ul>
<li><strong>Coefficient Interpretation:</strong> What do the regression coefficients actually mean in this context?</li>
<li><strong>The Problem of Non-Linearity:</strong> Can adding variables to a regression equation flip the sign of a coefficient while still making it appear significant?</li>
</ul>
<p><strong>Write like a data science consultant:</strong> Your report should help someone understand not just what the numbers show, but why they’re dangerous and what to do about it.</p>
</div>
</div>
</section>
</section>
<section id="sec-regression-concepts" class="level2">
<h2 class="anchored" data-anchor-id="sec-regression-concepts">Essential Regression Concepts 🎯</h2>
<p>Before diving into the challenge, let’s review the key regression concepts you’ll need. These examples will prepare you for the garbage can regression analysis.</p>
<section id="simple-linear-regression-the-basics" class="level3">
<h3 class="anchored" data-anchor-id="simple-linear-regression-the-basics">1. Simple Linear Regression: The Basics</h3>
<p>Let’s start with a basic linear regression to understand the mechanics:</p>
<div id="cell-simple-regression-python" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficient: 1.949
Intercept: 3.592
R-squared: 0.915</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="simple-regression-python" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/simple-regression-python-output-2.png" width="663" height="374" class="figure-img"></p>
<figcaption>Python simple linear regression example</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="multiple-regression-adding-complexity" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-adding-complexity">2. Multiple Regression: Adding Complexity</h3>
<p>Now let’s see how multiple variables interact:</p>
<div id="cell-multiple-regression-python" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients: [1.96423174 0.216209  ]
Intercept: 4.969
R-squared: 0.867</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="multiple-regression-python" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/multiple-regression-python-output-2.png" width="710" height="739" class="figure-img"></p>
<figcaption>Python multiple regression example</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Statistical Significance at 5% Level
</div>
</div>
<div class="callout-body-container callout-body">
<p>A coefficient is <strong>statistically significant</strong> when its p-value is less than 0.05.</p>
<ul>
<li><strong>p &lt; 0.05</strong>: Statistically significant</li>
<li><strong>p ≥ 0.05</strong>: Not statistically significant</li>
</ul>
<section id="understanding-scientific-notation-in-p-values" class="level3">
<h3 class="anchored" data-anchor-id="understanding-scientific-notation-in-p-values">Understanding Scientific Notation in P-values</h3>
<p>Sometimes you’ll see p-values written in scientific notation like <code>7.89e-4</code>. Don’t panic! This is just a way to write very small numbers:</p>
<ul>
<li><strong>7.89e-4</strong> means 7.89 × 10⁻⁴ = 0.000789</li>
<li><strong>2.34e-6</strong> means 2.34 × 10⁻⁶ = 0.00000234</li>
<li><strong>1.23e-2</strong> means 1.23 × 10⁻² = 0.0123</li>
</ul>
<p><strong>The key rule:</strong> If you see “e-” in a p-value, it’s always a very small number (less than 1). The number after “e-” tells you how many zeros come before the first non-zero digit.</p>
<p><strong>Examples:</strong> - 7.89e-4 = 0.000789 (less than 0.05, so significant!) - 2.34e-6 = 0.00000234 (way less than 0.05, so very significant!) - 1.23e-2 = 0.0123 (less than 0.05, so significant!)</p>
<p><strong>Remember:</strong> Statistical significance doesn’t mean the effect is large or important - it just means we’re confident the effect isn’t zero.</p>
</section>
</div>
</div>
</section>
</section>
<section id="the-problem-of-non-linearity-a-deeper-look" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-of-non-linearity-a-deeper-look">The Problem of Non-Linearity: A Deeper Look</h2>
<p>The “garbage can regression” problem occurs when we include variables in our regression models that create misleading results, even when they appear statistically significant. This happens in several ways:</p>
<ol type="1">
<li><strong>Random correlations:</strong> Even random variables can appear correlated by chance</li>
<li><strong>Overfitting:</strong> More variables can improve fit without improving understanding</li>
<li><strong>Multiple testing:</strong> The more variables we test, the more likely we are to find spurious relationships</li>
<li><strong>Non-linear relationships:</strong> Variables with U-shaped, exponential, or other non-linear relationships with the outcome are forced into a linear framework, creating misleading coefficients</li>
</ol>
<section id="why-this-matters" class="level3">
<h3 class="anchored" data-anchor-id="why-this-matters">Why This Matters</h3>
<p>In the real world, non-linear relationships can lead to:</p>
<ul>
<li><strong>False policy recommendations:</strong> Basing decisions on spurious correlations or false causal relationships</li>
<li><strong>Wasted resources:</strong> Pursuing interventions that don’t actually work</li>
<li><strong>Loss of credibility:</strong> When results can’t be replicated or don’t make sense</li>
<li><strong>Ethical issues:</strong> Making decisions that affect people’s lives based on bad science</li>
</ul>
</section>
<section id="the-solution" class="level3">
<h3 class="anchored" data-anchor-id="the-solution">The Solution</h3>
<p>The key is to always ask:</p>
<ol type="1">
<li><strong>Does this make theoretical sense?</strong> Is there a plausible mechanism?</li>
<li><strong>Is the relationship robust?</strong> Does it hold across different samples and specifications?</li>
<li><strong>Are we overfitting?</strong> Do we have enough data relative to the number of variables?</li>
<li><strong>Can we interpret the coefficients?</strong> Do the results tell a coherent story?</li>
<li><strong>Is the relationship truly linear?</strong> Check for non-linear patterns that linear regression can’t capture</li>
<li><strong>Are we forcing the wrong functional form?</strong> Consider if polynomial terms, interactions, or transformations are needed</li>
<li><strong>Split the sample into meaningful subsets:</strong> Analyze different “statistical regimes” to see if relationships hold consistently across different parts of your data</li>
<li><strong>Use graphical diagnostics:</strong> Don’t rely blindly on “canned” regressions—visualize the relationships to understand what’s really happening</li>
</ol>
<p>Remember: <strong>Correlation is not causation, and regression coefficients can lie!</strong> 📊</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>